#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"

"$root/tests/run_firmware_tool_tests.sh"
"$root/tests/run_f401_bundle_tool_tests.sh"
if command -v pwsh >/dev/null 2>&1; then
  pwsh -NoLogo -NoProfile -File "$root/tests/run_firmware_tool_powershell_tests.ps1"
fi
"$root/tests/run_debug_tests.sh"
"$root/tests/run_board_profile_tests.sh"
"$root/tests/run_a00_image_multiplex_tests.sh"
"$root/tests/run_wbmp_tests.sh"
"$root/tests/run_bounded_string_tests.sh"
"$root/tests/run_dfu_splash_tests.sh"
"$root/tests/run_display_font_tests.sh"
"$root/tests/run_uc1609_transport_tests.sh"
"$root/tests/run_fmk_converter_tests.sh"
"$root/tests/run_focal_tests.sh"
"$root/tests/run_flash_capacity_probe_tests.sh"
"$root/tests/run_spi_nor_sfdp_tests.sh"
"$root/tests/run_keyboard_tests.sh"
"$root/tests/run_keyboard_layout_profile_tests.sh"
"$root/tests/run_ledcontrol_tests.sh"
"$root/tests/run_loadable_app_api_tests.sh"
"$root/tests/run_loadable_module_format_tests.sh"
"$root/tests/run_loadable_module_pack_tests.sh"
"$root/tests/run_m61_text_tests.sh"
"$root/tests/run_mk_math_tests.sh"
"$root/tests/run_mk61_ref_tests.sh"
"$root/tests/run_mkc_tests.sh"
if command -v pwsh >/dev/null 2>&1; then
  pwsh -NoLogo -NoProfile -File "$root/tests/run_mkc_powershell_tests.ps1"
fi
"$root/tests/run_memory_buffer_tests.sh"
"$root/tests/run_storage_geometry_tests.sh"
"$root/tests/run_msc_scsi_safety_tests.sh"
"$root/tests/run_program_store_tests.sh"
"$root/tests/run_runtime_peripherals_tests.sh"
"$root/tests/run_settings_journal_tests.sh"
"$root/tests/run_startup_splash_tests.sh"
"$root/tests/run_terminal_tests.sh"
"$root/tests/run_text_editor_tests.sh"
"$root/tests/run_tinybasic_tests.sh"
"$root/tests/run_usb_screen_protocol_tests.sh"
"$root/tests/run_usb_screen_surface_tests.sh"
"$root/tests/run_usb_screen_virtual_keys_tests.sh"
"$root/tests/run_virtual_fat_tests.sh"
