STAT=0;CLAIM=0;REPS=1;MATW=0;MATB=0
AQ=WK;IF SIDE=-1 AQ=BK
AS=-SIDE
LOCAL attack
:check
CHECK=(AT>0);STATUS_CURSOR=0
GLSTATE=&STATUS_CURSOR;GLSIDE=SIDE;GLMODE=2;GLPIECE=0;GLTYPE=0
CALL legal :moves
:moves
IF GLMOVE>0 G.:material
STAT=3;IF CHECK=1 STAT=(SIDE=-1)+2*(SIDE=1)
G.:done
:material
B=0;N=0;X=0;C=-1;D=0
FOR I=21 TO 98
P=@(I);K=ABS(P)
IF (K=0) OR (K>6) G.:next
V=2;IF K=2 V=6
IF K=3 V=7
IF K=4 V=10
IF K=5 V=20
IF K=6 V=0
IF P>0 MATW=MATW+V
IF P<0 MATB=MATB+V
IF (K=1) OR (K=4) OR (K=5) X=1
IF K=2 N=N+1
IF K#3 G.:next
B=B+1;A=(I MOD 10+INT(I/10)) MOD 2
IF C=-1 C=A
IF C#A D=1
:next
NEXT I
IF (X=0) AND (N=0) AND (D=0) STAT=4
IF (X=0) AND (B=0) AND (N<2) STAT=4
IF STAT>0 G.:done
IF HALF>=150 STAT=6
IF STAT>0 G.:done
CALL repeat :repetition
:repetition
REPS=REPRESULT
IF REPS>=5 STAT=5
IF REPS>=3 CLAIM=1
IF HALF>=100 CLAIM=CLAIM+2
:done
RET
