# Этот файл настраивает анализатор, который статически проверяет код Dart
# на ошибки, предупреждения и нарушения правил.
#
# Найденные анализатором проблемы отображаются в интерфейсе IDE с поддержкой
# Dart (https://dart.dev/tools#ides-and-editors). Анализатор также можно
# запустить из командной строки командой `flutter analyze`.

# Следующая строка включает набор рекомендуемых правил для приложений, пакетов
# и плагинов Flutter, способствующих хорошему стилю кода.
include: package:flutter_lints/flutter.yaml

linter:
  # Применяемые к проекту правила можно настроить в разделе ниже: отключить
  # правила из подключённого выше `package:flutter_lints/flutter.yaml` или
  # включить дополнительные. Список всех правил и документация опубликованы
  # на https://dart.dev/lints.
  #
  # Вместо отключения правила для всего проекта в разделе ниже его можно
  # подавить для одной строки кода или конкретного файла Dart с помощью
  # синтаксиса `// ignore: name_of_lint` и `// ignore_for_file: name_of_lint`
  # в строке или файле, где возникает нарушение.
  rules:
    # avoid_print: false  # Раскомментируйте, чтобы отключить правило `avoid_print`
    # prefer_single_quotes: true  # Раскомментируйте, чтобы включить правило `prefer_single_quotes`

# Дополнительные сведения об этом файле:
# https://dart.dev/guides/language/analysis-options
