// Generated by tools/turochamp/assemble.py; test wire addresses.
#pragma once
namespace tc {
constexpr int SIDE=120;
constexpr int RIGHTS=121;
constexpr int EP=122;
constexpr int HALF=123;
constexpr int FULL=124;
constexpr int WK=125;
constexpr int BK=126;
constexpr int LASTCAP=127;
constexpr int CW=128;
constexpr int CB=129;
constexpr int HCOUNT=130;
constexpr int HEP=131;
constexpr int MODE=132;
constexpr int CUR=133;
constexpr int SEL=134;
constexpr int PROMO=135;
constexpr int RESULT=136;
constexpr int CHECK=137;
constexpr int CLAIM=138;
constexpr int MOVE=139;
constexpr int LAST=140;
constexpr int COUNT=141;
constexpr int REPS=142;
constexpr int CP=143;
constexpr int PHASE=144;
constexpr int SP=145;
constexpr int NODES=146;
constexpr int DFS=147;
constexpr int ROOT=148;
constexpr int BEST=149;
constexpr int ROOTPOS=150;
constexpr int ROOTVAL=151;
constexpr int ALPHA=152;
constexpr int LFRAME=153;
constexpr int GLSTATE=154;
constexpr int GLMOVE=155;
constexpr int GLSIDE=156;
constexpr int GLMODE=157;
constexpr int GLPIECE=158;
constexpr int GLTYPE=159;
constexpr int APMOVE=160;
constexpr int APFRAME=161;
constexpr int APSIDE=162;
constexpr int AQ=163;
constexpr int AS=164;
constexpr int AT=165;
constexpr int AN=166;
constexpr int STAT=167;
constexpr int MATW=168;
constexpr int MATB=169;
constexpr int PE=170;
constexpr int PCS=171;
constexpr int REPDEP=172;
constexpr int REPRESULT=173;
constexpr int ED=174;
constexpr int EF=175;
constexpr int EC=176;
constexpr int ES=177;
constexpr int ECHECK=178;
constexpr int ETHREAT=179;
constexpr int ROOTC=180;
constexpr int LEVEL=181;
constexpr int QLIMIT=182;
constexpr int SIM=183;
constexpr int HIST=184;
constexpr int STACK=222;
constexpr int RETURNS=278;
constexpr int GEN_CURSOR=288;
constexpr int E_CURSOR=289;
constexpr int E_MOVE=290;
constexpr int E_UNDO=291;
constexpr int G_UNDO=293;
constexpr int STATUS_CURSOR=295;
constexpr int RP_META=296;
constexpr int RP_KEY=301;
constexpr int RP_HCUR=306;
constexpr int RP_STATE=307;
constexpr int RP_DEPTH=308;
constexpr int RP_COUNT=309;
constexpr int RP_BRANCH=310;
constexpr int UI_ITER=311;
constexpr int UI_ACTION=312;
constexpr int UI_PHASE=313;
constexpr int UI_KEY=314;
constexpr int UI_TEST=315;
constexpr int UI_MESSAGE=316;
constexpr int BOOK_ENABLED=317;
constexpr int BOOK_NODE=318;
constexpr int UI_VIEW=319;
constexpr int UI_FLAGS=320;
constexpr int ROOTCURSOR=321;
constexpr int ROOTEVAL=322;
constexpr int ROOTMAT=323;
constexpr int ROOTTMP=324;
constexpr int SEARCH_CUR=326;
constexpr int RETVAL=327;
constexpr int RP_BACK=328;
constexpr int RP_FORWARD=329;
constexpr int H_MOVE=330;
constexpr int BOOK_ACTION=331;
constexpr int BOOK_MOVE=332;
constexpr int DRAW_REASON=333;
constexpr int BOOK_NEXT=334;
constexpr int TMP=335;
constexpr int DIRN=336;
constexpr int DIRS=344;
constexpr int M_INIT=1;
constexpr int M_GAME=2;
constexpr int M_BOARD=3;
constexpr int M_PSEUDO=4;
constexpr int M_LEGAL=5;
constexpr int M_MAKE=7;
constexpr int M_UNMAKE=8;
constexpr int M_STATUS=9;
constexpr int M_REPEAT=10;
constexpr int M_EVAL=11;
constexpr int M_SEARCH=12;
constexpr int M_TURN=13;
constexpr int M_HISTORY=14;
constexpr int M_MENU=15;
constexpr int M_PROMOTE=16;
constexpr int M_CLAIM=17;
constexpr int M_CASTLE=20;
constexpr int M_MOBILITY=21;
constexpr int M_THREAT=22;
constexpr int M_EP=23;
constexpr int M_RKEY=24;
constexpr int M_RSTEP=25;
constexpr int M_NODE=26;
constexpr int M_CLAIMS=28;
constexpr int M_HELP=29;
struct Module { int id; const char* name; };
constexpr Module MODULES[] = {
  {M_INIT, "init"},
  {M_GAME, "game"},
  {M_BOARD, "board"},
  {M_PSEUDO, "pseudo"},
  {M_LEGAL, "legal"},
  {M_MAKE, "make"},
  {M_UNMAKE, "unmake"},
  {M_STATUS, "status"},
  {M_REPEAT, "repeat"},
  {M_EVAL, "eval"},
  {M_SEARCH, "search"},
  {M_TURN, "turn"},
  {M_HISTORY, "history"},
  {M_MENU, "menu"},
  {M_PROMOTE, "promote"},
  {M_CLAIM, "claim"},
  {M_CASTLE, "castle"},
  {M_MOBILITY, "mobility"},
  {M_THREAT, "threat"},
  {M_EP, "ep"},
  {M_RKEY, "rkey"},
  {M_RSTEP, "rstep"},
  {M_NODE, "node"},
  {M_CLAIMS, "claims"},
  {M_HELP, "help"},
};
}
