#!/usr/bin/env python3
"""Generate exact-size M8 C string literals from readable UTF-8 JSON."""

import argparse
import json
from pathlib import Path

from m8_codec import encode


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "code/mk8_strings.json"
OUTPUT = ROOT / "code/mk8_strings.inc"
def c_literal(data: bytes) -> str:
    pieces = []
    for byte in data:
        if 0x20 <= byte <= 0x7E and byte not in (ord('"'), ord('\\')):
            pieces.append(chr(byte))
        elif byte == ord('"'):
            pieces.append('\\"')
        elif byte == ord('\\'):
            pieces.append('\\\\')
        else:
            pieces.append(f"\\{byte:03o}")
    return '"' + ''.join(pieces) + '"'


def generated() -> str:
    values = json.loads(SOURCE.read_text(encoding="utf-8"))
    if not isinstance(values, dict) or not values:
        raise ValueError("MK8 catalog must be a non-empty JSON object")
    lines = [
        "// Generated by tools/generate_mk8_strings.py; do not edit.",
        "// Source: code/mk8_strings.json.",
    ]
    for name, text in values.items():
        if not name.isidentifier() or name.upper() != name or not isinstance(text, str):
            raise ValueError(f"invalid MK8 catalog entry: {name!r}")
        payload = encode(text)
        lines.append(f"#define M8_{name} {c_literal(payload)}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generated()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="ascii") != content:
            raise SystemExit(f"stale generated file: {OUTPUT}")
        return 0
    OUTPUT.write_text(content, encoding="ascii", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
