#!/usr/bin/env python3
"""Pack reviewed native monochrome atlases; no font engine is needed to build FW."""

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ATLAS_DIR = ROOT / "tools/.fmk-font/ui-atlases"
NAMES = ("dejavu-12", "dejavu-14", "dejavu-16",
         "roboto-12", "roboto-14", "roboto-16")
SOURCE_HASHES = {
    "dejavu-12": "e98720dfdc9fecb4954b536912c720ec6934d0a8b9c05cf88c33bdb16a6438f5",
    "dejavu-14": "604c5750eb369d380790710ddc6290b44bcb13acd70d46d331d3d14258defa34",
    "dejavu-16": "bb5e3a6f0e4502dadfd5da86bcbd9f34c7e8ba93675f6e1ff00a498ab79921b1",
    "roboto-12": "0d7c0a7966f280d3211a14f8442968dcc22c9ead70e14f5ca187bf771387a0c3",
    "roboto-14": "89e7a33561ed37659d58da7027f8e75025ee368f1d491eac90781e5c2666d17a",
    "roboto-16": "fcb310da83adc4b1ecaaf17bb1597a37e9d1229fb441288a1b64b5e7a439baf5",
}
LINE_GAPS = {12: 1, 14: 2, 16: 2}


def require(condition, message):
    if not condition:
        raise ValueError(message)


def load_atlases(directory=ATLAS_DIR):
    result = []
    for name in NAMES:
        raw = (directory / f"{name}.json").read_bytes()
        require(hashlib.sha256(raw).hexdigest() == SOURCE_HASHES[name],
                f"{name}: reviewed source SHA-256 changed")
        atlas = json.loads(raw)
        require(atlas["schema"] == 1 and
                atlas["height"] == int(name.rsplit("-", 1)[1]),
                f"{name}: unexpected metrics")
        require(atlas["height"] == atlas["ascent"] + atlas["descent"],
                f"{name}: inconsistent line box")
        glyphs = {glyph["codepoint"]: glyph for glyph in atlas["glyphs"]}
        require(len(glyphs) == len(atlas["glyphs"]), f"{name}: duplicate glyph")
        for cp, glyph in glyphs.items():
            w, h = glyph["width"], glyph["height"]
            x, y = glyph["safe_bearing_x"], glyph["bearing_y"]
            require(1 <= w <= 16 and 1 <= h <= atlas["height"],
                    f"{name}/{cp}: unsupported dimensions")
            require(0 <= x <= 16 and x + w < glyph["advance"] <= 32,
                    f"{name}/{cp}: no safe inter-glyph gap")
            require(0 <= atlas["ascent"] - y and h - y <= atlas["descent"],
                    f"{name}/{cp}: outside baseline envelope")
            require(len(glyph["rows"]) == h and all(
                len(row) == w and set(row) <= {"0", "1"} for row in glyph["rows"]),
                f"{name}/{cp}: malformed raster")
        atlas["by_codepoint"] = glyphs
        result.append(atlas)
    repertoire = sorted(result[0]["by_codepoint"])
    require(len(repertoire) == 169 and repertoire[:95] == list(range(32, 127)),
            "unexpected repertoire")
    for name, atlas in zip(NAMES, result):
        actual = set(atlas["by_codepoint"])
        require(actual <= set(repertoire) and
                set(repertoire) - actual == set(atlas["missing"]),
                f"{name}: inconsistent missing characters")
        if name.startswith("dejavu"):
            require(not atlas["missing"], "DejaVu must cover fallback repertoire")
    for i in (3, 4, 5):
        require(all(result[i][key] == result[i - 3][key]
                    for key in ("height", "ascent", "descent")),
                "fallback baseline differs")
    return result, repertoire


def pack_glyph(glyph):
    bits = "".join(glyph["rows"])
    bits += "0" * (-len(bits) % 8)
    return bytes(int(bits[i:i + 8], 2) for i in range(0, len(bits), 8))


def generate(directory=ATLAS_DIR):
    atlases, repertoire = load_atlases(directory)
    lines = ["// Generated by tools/generate_ui_fonts.py; do not edit.",
             "// Source/permissions: tools/.fmk-font/ui-atlases/README.md.",
             "// Row-major MSB-first bits, tightly packed within each glyph.",
             "static constexpr uint16_t MISSING_OFFSET = 0xFFFFU;",
             f"static constexpr unsigned GLYPH_COUNT = {len(repertoire)};",
             "static const uint16_t CODEPOINTS[GLYPH_COUNT] = {"]
    for start in range(0, len(repertoire), 12):
        lines.append("  " + ", ".join(f"0x{cp:04X}" for cp in repertoire[start:start + 12]) + ",")
    lines.append("};")
    bitmap_bytes = 0
    for name, atlas in zip(NAMES, atlases):
        symbol = name.upper().replace("-", "_")
        bitmap = bytearray()
        offsets = {}
        records = []
        for cp in repertoire:
            glyph = atlas["by_codepoint"].get(cp)
            if glyph is None:
                records.append("  {MISSING_OFFSET, 0, 0, 0, 0, 0},")
                continue
            packed = pack_glyph(glyph)
            # Whole-glyph byte strings may share storage without changing shape.
            if packed not in offsets:
                offsets[packed] = len(bitmap)
                bitmap.extend(packed)
            records.append("  {%d, %d, %d, %d, %d, %d}," % (
                offsets[packed], glyph["width"], glyph["height"],
                glyph["safe_bearing_x"], glyph["bearing_y"], glyph["advance"]))
        require(len(bitmap) < 0xFFFF, f"{name}: bitmap offset overflow")
        bitmap_bytes += len(bitmap)
        lines.extend((f"static const uint8_t {symbol}_BITMAP[] = {{",))
        for start in range(0, len(bitmap), 16):
            lines.append("  " + ", ".join(f"0x{v:02X}" for v in bitmap[start:start + 16]) + ",")
        lines.extend(("};", f"static const GlyphRecord {symbol}_RECORDS[GLYPH_COUNT] = {{"))
        lines.extend(records)
        lines.append("};")
    lines.append("static const FaceData FACES[] = {")
    for name, atlas in zip(NAMES, atlases):
        symbol = name.upper().replace("-", "_")
        lines.append("  {%s_RECORDS, %s_BITMAP, {%d, %d, %d, %d, %d}}," % (
            symbol, symbol, atlas["height"], atlas["ascent"], atlas["descent"],
            LINE_GAPS[atlas["height"]], atlas["ppem"]))
    lines.extend(("};", f"// Packed bitmap bytes (all {len(NAMES)} faces): {bitmap_bytes}.", ""))
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "code/ui_font_data.inc")
    parser.add_argument("--check", action="store_true", help="fail if generated file differs")
    args = parser.parse_args()
    expected = generate()
    if args.check:
        require(args.output.read_text() == expected, "generated UI font data is stale")
        print(f"UI font data matches all {len(NAMES)} reviewed atlases")
    else:
        args.output.write_text(expected)
        print(f"Generated {args.output}")


if __name__ == "__main__":
    main()
