#!/usr/bin/env python3
"""Pack reviewed native monochrome atlases; no font engine is needed to build FW."""

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ATLAS_DIR = ROOT / "tools/.fmk-font/ui-atlases"
NAMES = ("pixel-12", "pixel-14", "pixel-16")
EXPECTED_HEIGHTS = {"pixel-12": 12, "pixel-14": 14, "pixel-16": 17}
SOURCE_HASHES = {
    "pixel-12": "67741710e4d63c1cdda6129bae7c0942ee0a8ae05e61e8bca0af273c10c88584",
    "pixel-14": "e12017456c29b40d6c560609e021d40ce6c5ca6b5c44772e41a714111c8d9f50",
    "pixel-16": "de535e79b99b916e6e89fa9fbfc4fafab74aa96d8d719ace2705b89409820366",
}
LINE_GAPS = {12: 1, 14: 2, 17: 2}


def require(condition, message):
    if not condition:
        raise ValueError(message)


def load_atlases(directory=ATLAS_DIR):
    result = []
    for name in NAMES:
        raw = (directory / f"{name}.json").read_bytes()
        require(hashlib.sha256(raw).hexdigest() == SOURCE_HASHES[name],
                f"{name}: reviewed source SHA-256 changed")
        atlas = json.loads(raw)
        require(atlas["schema"] == 1 and
                atlas["height"] == EXPECTED_HEIGHTS[name],
                f"{name}: unexpected metrics")
        require(atlas["height"] == atlas["ascent"] + atlas["descent"],
                f"{name}: inconsistent line box")
        glyphs = {glyph["codepoint"]: glyph for glyph in atlas["glyphs"]}
        require(len(glyphs) == len(atlas["glyphs"]), f"{name}: duplicate glyph")
        for cp, glyph in glyphs.items():
            w, h = glyph["width"], glyph["height"]
            x, y = glyph["safe_bearing_x"], glyph["bearing_y"]
            require(1 <= w <= 16 and 1 <= h <= atlas["height"],
                    f"{name}/{cp}: unsupported dimensions")
            require(0 <= x <= 16 and x + w < glyph["advance"] <= 32,
                    f"{name}/{cp}: no safe inter-glyph gap")
            require(0 <= atlas["ascent"] - y and h - y <= atlas["descent"],
                    f"{name}/{cp}: outside baseline envelope")
            require(len(glyph["rows"]) == h and all(
                len(row) == w and set(row) <= {"0", "1"} for row in glyph["rows"]),
                f"{name}/{cp}: malformed raster")
        atlas["by_codepoint"] = glyphs
        result.append(atlas)
    repertoire = sorted(set(result[0]["by_codepoint"]) | set(result[0]["missing"]))
    require(len(repertoire) == 169 and repertoire[:95] == list(range(32, 127)),
            "unexpected repertoire")
    for name, atlas in zip(NAMES, result):
        actual = set(atlas["by_codepoint"])
        require(actual <= set(repertoire) and
                set(repertoire) - actual == set(atlas["missing"]),
                f"{name}: inconsistent missing characters")
        require(set(atlas["missing"]) == {0x2264, 0x2265},
                f"{name}: only ≤/≥ may use the explicit ASCII fallback")
    return result, repertoire


def pack_glyph(glyph):
    bits = "".join(glyph["rows"])
    bits += "0" * (-len(bits) % 8)
    return bytes(int(bits[i:i + 8], 2) for i in range(0, len(bits), 8))


def generate(directory=ATLAS_DIR):
    atlases, repertoire = load_atlases(directory)
    lines = ["// Generated by tools/generate_ui_fonts.py; do not edit.",
             "// Source/permissions: tools/.fmk-font/ui-atlases/README.md.",
             "// Row-major MSB-first bits, tightly packed within each glyph.",
             "static constexpr uint16_t MISSING_OFFSET = 0xFFFFU;",
             f"static constexpr unsigned GLYPH_COUNT = {len(repertoire)};",
             "static const uint16_t CODEPOINTS[GLYPH_COUNT] = {"]
    for start in range(0, len(repertoire), 12):
        lines.append("  " + ", ".join(f"0x{cp:04X}" for cp in repertoire[start:start + 12]) + ",")
    lines.append("};")
    bitmap_bytes = 0
    for name, atlas in zip(NAMES, atlases):
        symbol = name.upper().replace("-", "_")
        bitmap = bytearray()
        offsets = {}
        records = []
        for cp in repertoire:
            glyph = atlas["by_codepoint"].get(cp)
            if glyph is None:
                records.append("  {MISSING_OFFSET, 0, 0, 0, 0, 0},")
                continue
            packed = pack_glyph(glyph)
            # Whole-glyph byte strings may share storage without changing shape.
            if packed not in offsets:
                offsets[packed] = len(bitmap)
                bitmap.extend(packed)
            records.append("  {%d, %d, %d, %d, %d, %d}," % (
                offsets[packed], glyph["width"], glyph["height"],
                glyph["safe_bearing_x"], glyph["bearing_y"], glyph["advance"]))
        require(len(bitmap) < 0xFFFF, f"{name}: bitmap offset overflow")
        bitmap_bytes += len(bitmap)
        lines.extend((f"static const uint8_t {symbol}_BITMAP[] = {{",))
        for start in range(0, len(bitmap), 16):
            lines.append("  " + ", ".join(f"0x{v:02X}" for v in bitmap[start:start + 16]) + ",")
        lines.extend(("};", f"static const GlyphRecord {symbol}_RECORDS[GLYPH_COUNT] = {{"))
        lines.extend(records)
        lines.append("};")
    lines.append("static const FaceData FACES[] = {")
    for name, atlas in zip(NAMES, atlases):
        symbol = name.upper().replace("-", "_")
        lines.append("  {%s_RECORDS, %s_BITMAP, {%d, %d, %d, %d, %d}}," % (
            symbol, symbol, atlas["height"], atlas["ascent"], atlas["descent"],
            LINE_GAPS[atlas["height"]], atlas["ppem"]))
    lines.extend(("};", f"// Packed bitmap bytes (all {len(NAMES)} faces): {bitmap_bytes}.", ""))
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "code/ui_font_data.inc")
    parser.add_argument("--check", action="store_true", help="fail if generated file differs")
    args = parser.parse_args()
    expected = generate()
    if args.check:
        require(args.output.read_text() == expected, "generated UI font data is stale")
        print(f"UI font data matches all {len(NAMES)} reviewed atlases")
    else:
        args.output.write_text(expected)
        print(f"Generated {args.output}")


if __name__ == "__main__":
    main()
